# Select preferred mobile carrier. Do not use spaces.
# https://en.wikipedia.org/wiki/Mobile_country_code

GMS_MCC=282
GMS_MNC=04
GMS_ISO=ge
GMS_OPERATOR_NAME=Cellfie

# Change to 1 to enable verbose logging. Tag - GpayCountrySpoofer.
VERBOSE_LOGS=0
